### ISSUE TITLE
CKAN data API

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-opendata#11]
We need to setup the config to allow for the API to be used correctly.  Right now it uses localhost instead of a fully qualified url.  Think this may be due to the SSL hotfix but @orifito could you check or let me know before I change anything in the config file?

![screen shot 2015-05-11 at 12 37 51](https://cloud.githubusercontent.com/assets/2675262/7563184/e4e9346c-f7da-11e4-94a2-cc51090c9374.png)

**Comment by orifito** [comment]
When trying to use the API with SSL the following error appears:

```
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by orifito** [comment]
CKAN API is now available using the following endpoint: `http://opendata.akvo.org:8080`

**Comment by Lynngre** [comment]
Checking with CKAN re a resolution https://github.com/ckan/ckan/issues/2404
