### ISSUE TITLE
Incorrect time on server

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-opendata#5]
Time is two hours behind CEST.

![screen shot 2015-04-20 at 20 47 25](https://cloud.githubusercontent.com/assets/2675262/7237868/b9130e72-e79e-11e4-9ea1-7632f2f420f7.png)

**Comment by iperdomo** [comment]
Perhaps is just configured at UTC timezone ?

**Comment by Lynngre** [comment]
I think so but I'm not sure how are servers are setup.  Are they all set manually/individually or are these done via a script to update all automatically?  Or is it just a setting in CKAN itself somewhere?  Will investigate further tomorrow morning.

**Comment by orifito** [comment]
Servers time in general is configured through NTP protocol.
CKAN app seems to use UTC, even though the server's time is in CEST.

```
$ date
Tue Apr 21 08:19:17 CEST 2015
```
