### ISSUE TITLE
Datasets too large cause 413 error

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-opendata#8]
Datasets/files which are uploaded and are too large result in nginx error '413 Entity too large' in browser.

**Comment by orifito** [comment]
We need to configure nginx for that. 

```
client_max_body_size: Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. If the size in a request exceeds the configured value, the 413 (Request Entity Too Large) error is returned to the client.
```

Note that by default client_max_body_size is 1Mb. We would need some assessment from FLOW team to pick the right maximum allowed size.

**Comment by orifito** [comment]
Nginx has been configured to allow files up to 10MB. Please reopen the issue if that limit is not enough
